import './immersive-finale.css'
import { SpaceProfile } from '@/components/space-profile'

const projects = [
  ['AutiSmart', 'AI / Healthcare', 'Team-based Final Year Project for autism assessment and care support.', 'FYP-I A+ · FYP-II A- · Deployed and presented', 'https://alishah1029384756.github.io/AliShah1029384756/projects/autismart.html'],
  ['ClinicOS', 'Healthcare Operations', 'Clinic workflow software covering scheduling, records, and operational processes.', 'Systemized clinic operations lifecycle', 'https://alishah1029384756.github.io/AliShah1029384756/projects/clinicos.html'],
  ['SchoolIEP', 'Education', 'Structured IEP records and role-aware workflows for school environments.', 'Auditable education record lifecycle', 'https://alishah1029384756.github.io/AliShah1029384756/projects/schooliep.html'],
  ['EduCore', 'Open Learning', 'Student-first open-learning hub with 400+ curated technical resources.', 'Discoverable learning ecosystem', 'https://alishah1029384756.github.io/educore-open-learning-hub/'],
]

export default function Page() {
  return <main id="top"><SpaceProfile /><div className="portfolio-content">
    <section id="about" className="content-section shell"><div className="section-label">01 / About</div><div className="content-grid"><h2>Systems thinker <em>before coder.</em></h2><div><p className="large-copy">I’m Syed Muhammad Ali Naqvi, a FAST-NUCES BSCS graduate and full-stack developer building practical software for healthcare, education, and real-world workflows.</p><p className="muted-copy">My work combines product thinking with engineering fundamentals: understand the problem, design the system, document the decisions, then make the experience feel simple.</p><div className="principles"><span>01 — Clarity</span><span>02 — Ownership</span><span>03 — Learning</span></div></div></div></section>
    <section id="projects" className="content-section section-dark"><div className="shell"><div className="section-label">02 / Selected work</div><div className="section-head"><h2>Systems built.<br /><em>Problems solved.</em></h2><p>Explore the interactive project lab above or open a case study below.</p></div><div className="project-grid">{projects.map(([name, type, detail, result, link], index) => <article className="portfolio-card" key={name}><span className="card-number">0{index + 1}</span><span className="eyebrow">{type}</span><h3>{name}</h3><p>{detail}</p><div className="card-result"><b>Proof</b><span>{result}</span></div><a href={link} target="_blank" rel="noopener noreferrer">Explore project <span>↗</span></a></article>)}</div></div></section>
    <section id="skills" className="content-section shell"><div className="section-label">03 / Toolkit</div><div className="section-head"><h2>Strong foundations.<br /><em>Always learning.</em></h2><p>Practical experience across full-stack development, systems, data, and AI-assisted software.</p></div><div className="skills-list"><div><b>Languages</b><span>JavaScript · Python · C/C++ · Java · SQL</span></div><div><b>Frontend</b><span>React · HTML · CSS · Bootstrap · JavaScript</span></div><div><b>Backend</b><span>Node.js · Express · REST APIs · MongoDB · MySQL</span></div><div><b>AI / ML</b><span>Python · Scikit-learn · TensorFlow · OpenCV · AI APIs</span></div><div><b>Engineering</b><span>Git · GitHub · Postman · Linux · Testing · Documentation</span></div></div></section>
    <section id="experience" className="content-section section-dark"><div className="shell"><div className="section-label">04 / Experience</div><div className="timeline"><article><span>July 2026 — Present</span><h3>Digital Marketing Intern</h3><b>Atlas Honda Pakistan · Lahore</b><p>Working across digital communication, campaign support, and the operational details behind a large organization’s online presence.</p></article><article><span>August 2022 — Present</span><h3>CS Teacher · Computer Lab In-Charge · Hostel Warden</h3><b>Al Bethat Trust Boys School &amp; College</b><p>Teaching computer science and programming, managing practical lab environments, and supporting students through structured learning and day-to-day operations.</p></article><article><span>2022 — 2026</span><h3>Peer Mentor &amp; Technical Educator</h3><b>FAST-NUCES</b><p>Created learning resources, supported peers with university coursework and software projects, and built student-focused open-learning resources.</p></article></div></div></section>
    <section id="education" className="content-section shell"><div className="section-label">05 / Education</div><div className="education-card"><div><span className="eyebrow">FAST-NUCES · 2022 — 2026</span><h2>BS Computer Science</h2><p>Chiniot-Faisalabad Campus</p></div><div><b>Final Year Project</b><p>AutiSmart · FYP-I A+ · FYP-II A-</p><b>Focus</b><p>Full-stack systems, AI-assisted development, software architecture, systems fundamentals, and technical communication.</p></div></div></section>
    <section id="contact" className="contact-section"><div className="shell contact-grid"><div><div className="section-label">06 / Contact</div><h2>Have a meaningful system to build?</h2><p>Let’s talk about a product, a technical problem, or a team that values thoughtful engineering.</p></div><div className="contact-list"><a href="mailto:shahyed99@gmail.com"><span>Email</span><b>shahyed99@gmail.com</b><i>↗</i></a><a href="https://www.linkedin.com/in/ali-naqvi-1a9576331" target="_blank" rel="noopener noreferrer"><span>LinkedIn</span><b>Connect professionally</b><i>↗</i></a><a href="https://github.com/AliShah1029384756" target="_blank" rel="noopener noreferrer"><span>GitHub</span><b>Explore the code</b><i>↗</i></a></div></div></section>
    <footer className="site-footer shell"><span>© 2026 Syed Muhammad Ali Naqvi</span><span>Built with clarity.</span></footer>
  </div></main>
}

export const dynamic = 'force-static'